events {
    worker_connections 1024;
}

http {

    upstream servidores {
        server nodo1:8000;
        server nodo2:8000;
        server nodo3:8000;
    }

    server {
        listen 80;

        # Tráfico de clientes → balanceado entre nodos
        location / {
            proxy_pass http://servidores;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Health check de nginx mismo
        location /nginx-health {
            return 200 '{"status": "ok"}';
            add_header Content-Type application/json;
        }
    }
}