FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY suscriptor.py .

RUN mkdir -p logs

ENV RABBITMQ_HOST=rabbitmq

EXPOSE 8000

CMD ["python", "suscriptor.py"]