FROM python:3.11-slim

WORKDIR /app

# Dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Código
COPY publicador.py .

# Carpeta logs
RUN mkdir -p logs

# Variables por defecto (Kubernetes las puede sobrescribir)
ENV RABBITMQ_HOST=rabbitmq

EXPOSE 9100

CMD ["python", "publicador.py"]