apiVersion: batch/v1
kind: Job
metadata:
  name: setup-retry
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: setup
          image: setup-retry:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq