apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-setup
  namespace: sobel
spec:
  template:
    spec:
      nodeSelector:
        nodegroup: apps
      tolerations:
        - key: nodegroup
          value: apps
          effect: NoSchedule
      restartPolicy: OnFailure
      containers:
        - name: setup
          image: gcr.io/tp3-gcp-497003/sobel-setup:latest
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq.sobel.svc.cluster.local"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: user
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: pass
